name: Deploy to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install huggingface_hub

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
          from huggingface_hub import HfApi
          api = HfApi(token=HF_TOKEN)
          api.upload_folder(
              folder_path='.',
              repo_id='analyticsbyted/CIFAR10-Classifier',
              repo_type='space'
          )
          "