name: Deploy to Hugging Face Hub

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        uses: huggingface/push-to-hub-action@main
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_id: "analyticsbyted/CIFAR10-Classifier"
          repo_type: space
          target_path: "."
